import webbrowser

class MovieSites:
    def __init__(self):
        self.SITE_URLS = {
        "Netflix": "https://www.netflix.com",
        "Amazon Prime Video": "https://www.primevideo.com",
        "Disney+": "https://www.disneyplus.com",
        "HBO Max": "https://www.hbomax.com",
        "Hulu": "https://www.hulu.com",
        "Apple TV+": "https://tv.apple.com",
        "Peacock": "https://www.peacocktv.com",
        "Paramount+": "https://www.paramountplus.com",
        "Crunchyroll": "https://www.crunchyroll.com",
        "Shudder": "https://www.shudder.com",
        "Sling TV": "https://www.sling.com",
        "YouTube": "https://www.youtube.com",
        "Google TV": "https://tv.google",
        "Vudu": "https://www.vudu.com",
        "Tubi": "https://tubitv.com",
        "Pluto TV": "https://pluto.tv",
        "Kanopy": "https://www.kanopy.com",
        "BritBox": "https://www.britbox.com",
        "Acorn TV": "https://acorn.tv",
        "Mubi": "https://mubi.com",
        "Criterion Channel": "https://www.criterionchannel.com",
        "Rakuten TV": "https://rakuten.tv",
        "Plex": "https://www.plex.tv",
        "Showtime Anytime": "https://www.showtimeanytime.com",
        "Starz Play": "https://www.starz.com",
        "Discovery+": "https://www.discoveryplus.com",
        "BBC iPlayer": "https://www.bbc.co.uk/iplayer",
        "ITV Hub": "https://www.itv.com/hub",
        "All 4": "https://www.channel4.com",
        "Sky Go": "https://www.sky.com/skygo",
        "NOW TV": "https://www.nowtv.com",
        "Hotstar": "https://www.hotstar.com",
        "SonyLIV": "https://www.sonyliv.com",
        "ZEE5": "https://www.zee5.com",
        "Eros Now": "https://erosnow.com",
        "MX Player": "https://www.mxplayer.in",
        "JioCinema": "https://www.jiocinema.com",
        "Spuul": "https://spuul.com",
        "iQIYI": "https://www.iq.com",
        "Tencent Video": "https://v.qq.com",
        "Youku": "https://youku.com",
        "Bilibili": "https://www.bilibili.com",
        "Kocowa": "https://www.kocowa.com",
        "Viki": "https://www.viki.com",
        "Wavve": "https://www.wavve.com",
        "TVING": "https://www.tving.com",
        "Stan": "https://www.stan.com.au",
        "Foxtel Now": "https://www.foxtel.com.au/now",
        "Binge": "https://binge.com.au",
        "Crave": "https://www.crave.ca",
        "CBC Gem": "https://gem.cbc.ca",
        "CTV": "https://www.ctv.ca",
        "Global TV": "https://www.globaltv.com",
        "Telemundo": "https://www.telemundo.com",
        "Pantaya": "https://www.pantaya.com",
        "ViX": "https://vix.com",
        "Claro Video": "https://www.clarovideo.com",
        "Movistar Play": "https://www.movistarplay.com",
        "Blim TV": "https://www.blimtv.com",
        "Globoplay": "https://globoplay.globo.com",
        "Oi Play": "https://www.oiplay.tv",
        "UOL Play": "https://play.uol.com.br",
        "DAZN": "https://www.dazn.com",
        "ESPN+": "https://www.espn.com/espnplus",
        "FuboTV": "https://www.fubo.tv",
        "CBS Sports": "https://www.cbssports.com",
        "NBC Sports": "https://www.nbcsports.com",
        "NFL Game Pass": "https://www.nfl.com/gamepass",
        "NBA League Pass": "https://www.nba.com/leaguepass",
        "MLB.TV": "https://www.mlb.com/live-stream-games",
        "NHL.TV": "https://www.nhl.com/tv",
        "WWE Network": "https://www.wwe.com/wwenetwork",
        "Funimation": "https://www.funimation.com",
        "AnimeLab": "https://www.animelab.com",
        "VRV": "https://vrv.co",
        "HiDive": "https://www.hidive.com",
        "Docsville": "https://www.docsville.com",
        "Curiosity Stream": "https://curiositystream.com",
        "MagellanTV": "https://www.magellantv.com",
        "History Vault": "https://www.historyvault.com",
        "Hallmark Movies Now": "https://www.hmnow.com",
        "Lifetime Movie Club": "https://www.lifetimemovieclub.com",
        "AMC+": "https://www.amcplus.com",
        "Sundance Now": "https://www.sundancenow.com",
        "Topic": "https://www.topic.com",
        "Arrow Player": "https://www.arrow-player.com",
        "Shout! Factory TV": "https://www.shoutfactorytv.com",
        "Popcornflix": "https://www.popcornflix.com",
        "Xumo": "https://www.xumo.com",
        "Crackle": "https://www.crackle.com",
        "Freevee": "https://www.amazon.com/freevee",
        "Rakuten Viki": "https://www.viki.com",
        "Joyn": "https://www.joyn.de",
        "Zattoo": "https://zattoo.com",
        "Waipu.tv": "https://waipu.tv",
        "MagentaTV": "https://www.telekom.com/en/magentatv",
        "RTL+": "https://rtlplus.de",
        "ProSiebenSat.1": "https://prosiebensat1.com",
        "Arte": "https://www.arte.tv",
        "France.tv": "https://www.france.tv",
        "Molotov": "https://www.molotov.tv",
        "RTBF Auvio": "https://www.rtbf.be/auvio",
        "RTÉ Player": "https://www.rte.ie/player",
        "Viaplay": "https://viaplay.com",
        "C More": "https://www.cmore.se",
        "SF Anytime": "https://www.sfanytime.com",
        "Yle Areena": "https://areena.yle.fi",
        "NRK TV": "https://tv.nrk.no",
        "SVT Play": "https://www.svtplay.se",
        "DR TV": "https://www.dr.dk/drtv",
        "TV2 Play": "https://play.tv2.dk",
        "Showmax": "https://www.showmax.com",
        "Net naija":"https://www.netnaija.com",
    }

    @staticmethod
    def build_smart_search(url, query):
        if "youtube" in url:
            return f"{url}/results?search_query={query}"
        else:
            return f"{url}/search?q={query}"
    @staticmethod
    def webgo(url):
        # edge_path = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe %s"
        webbrowser.open(url)

    def operate_movie_site(self, url):
        self.webgo(url)

    def search_movie_site(self, url, query):
        search_url = self.build_smart_search(url, query)
        self.webgo(search_url)


